build: false

environment:
  PYTHON: "C\\Python37"

  CONAN_REFERENCE: 'qt_test/0.0.2'
  CONAN_USERNAME: 'None'
  CONAN_LOGIN_USERNAME: 'None'
  CONAN_CHANNEL: 'None'

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      CONAN_VISUAL_VERSIONS: 17

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - cinst install cmake ninja
  - conan user

test_script:
  - python build.py
