---
app-id: io.github.jmuelbert.qtwidgettest
runtime: org.kde.Platform
runtime-version: 5.15-21.08
sdk: org.kde.Sdk
command: qtwidgettest
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=x11
  # Wayland access
  - --socket=wayland
  - --device=dri
  # Connectivity
  - --share=network
  # QtSingleApplication, allow other instances to see log files
  - --env=TMPDIR=/var/tmp
  # Allow loading files from anywhere
  - --filesystem=host:ro
  # Notification access
  - --talk-name=org.freedesktop.Notifications
  # System Tray Icon
  - --talk-name=org.kde.StatusNotifierWatcher
  - --own-name=org.kde.*
  - --own-name=io.github.jmuelbert.qtwidgettest
cleanup:
  - /include
  - /lib
  - /lib/cmake
  - /share/aclocal
  - /share/pkgconfig
  - /share/info
  - /share/man
  - /cmake
  - '*.a'
  - '*.la'
  - '*.cmake'
modules:
  - name: fmt
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
      - -DENABLE_CONAN=OFF
      - -DFMT_DOC=OFF
      - -DFMT_TEST=OFF
    sources:
      - type: archive
        url: https://github.com/fmtlib/fmt/releases/download/9.1.0/fmt-9.1.0.zip
        sha256: cceb4cb9366e18a5742128cb3524ce5f50e88b476f1e54737a47ffdf4df4c996
  - name: spdlog
    buildsystem: cmake-ninja
    builddir: true
    sources:
      - type: archive
        url: https://github.com/gabime/spdlog/archive/refs/tags/v1.10.0.tar.gz
        sha256: 697f91700237dbae2326b90469be32b876b2b44888302afbc7aceb68bcfe8224
  - name: qtwidgettest
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DENABLE_CONAN=OFF
      - -DBUILD_TESTING=OFF
      - -DENABLE_CACHE=ON
    sources:
      - type: dir
        path: ../
