---
name: qtcanonboilerplate
adopt-info: qtcanonboilerplate
icon: assets/icons/icons8-app-symbol-80.png

base: core20
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64

summary: A test.
description: qt_canon_boilerplate is a test app.

version: "0.6.0"

apps:
  qtcanonboilerplate:
    command: usr/bin/qt_canon_boilerplate
    common-id: com.github.jmuelbert.qt_canon_boilerplate
    extensions:
      - kde-neon
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
parts:
  qtcanonboilerplate:
    plugin: cmake
    source: .
    cmake-parameters:
      - "-DLGTM=ON"
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
    source-type: git
    parse-info:
      - usr/share/appdata/qt_canon_boilserplate.appdata.xml
    build-snaps:
      - kde-frameworks-5-qt-5-15-core20
    build-packages:
      - python
      - libmpfr-dev
      - libgmp-dev
      - kdoctools-dev
    stage-packages:
      - libmpfr6
      - libgmp10
    override-pull: |
      snapcraftctl pull

    after:
      - extra-cmake-modules

  extra-cmake-modules:
    source: https://github.com/KDE/extra-cmake-modules.git
    source-depth: 1
    source-tag: v5.93.0
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
    prime: [-./*]
