---
name: qtwidgettest
adopt-info: qtwidgettest
icon: assets/icons/icons8-app-symbol-80.png

base: core20
grade: devel
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64

summary: A test.
description: qt_canon_boilerplate is a test app.

version: '0.0.2'

apps:
  qtwidgettest:
    common-id: io.github.jmuelbert.qtwidgettest
    command: usr/local/bin/qtwidgettest
    desktop: usr/local/share/applications/io.github.jmuelbert.qtwidgettest.desktop

    extensions:
      - kde-neon
    environment:
      DISABLE_WAYLAND: 1
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7

parts:
  extra-cmake-modules:
    source: https://github.com/KDE/extra-cmake-modules.git
    source-depth: 1
    source-tag: v5.93.0
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
    prime: [-./*]
  qtwidgettest:
    after:
      - extra-cmake-modules
    source: .
    source-type: git
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_TESTING=OFF
      - -DBUILD_TESTING=OFF
      - -DENABLE_CONAN=OFF
    build-snaps:
      - kde-frameworks-5-qt-5-15-core20
    build-packages:
      - python
      - catch
      - libmpfr-dev
      - libfmt-dev
      - libspdlog-dev
      - libgmp-dev
      - kdoctools-dev
      - g++
      - make
      - qt5-default
      - git
    stage-packages:
      - dbus-x11
      - libgtk2.0-0
      - openssl
      - ca-certificates
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0

    parse-info:
      - usr/share/metainfo/io.github.jmuelbert.qtwidgettest.metainfo.xml

  runtime:
    plugin: nil
    stage-packages:
      - zlib1g
    prime:
      - '-usr/lib/x86_64-linux-gnu/libQt5*'
      - '-usr/lib/x86_64-linux-gnu/libqt5*'

  cleanup:
    after: # Make this part run last; list all your other parts here
      - qtwidgettest
      - runtime
    plugin: nil
    build-snaps: # List all content-snaps and base snaps you're using here
      - core20
      - kde-frameworks-5-qt-5-15-core20
      # override-prime: |
      #   set -eux
      #   for snap in "core20" "kde-frameworks-5-qt-5-15-core20"; do  # List all content-snaps and base snaps you're using here
      #     cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      #   done
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
