---
# GitHub Action to automate the identification of common misspellings in text files.
# https://github.com/codespell-project/actions-codespell
# https://github.com/codespell-project/codespell
name: codespell

# yamllint disable
on:
  # yamllint enable  push:
  push:
    branches: [main, develop, release-*]
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
