---
name: License Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # you can run this check locally as a pre-commit-hook by installing deno
      # and the running `deno run --unstable --allow-read https://deno.land/x/license_checker@v3.1.3/main.ts`.
      # see https://github.com/kt3k/deno_license_checker
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6